apiVersion: v1
kind: Service
metadata:
  name: postgres-server
  namespace: postgres-server
spec:
  selector:
    app: postgres-server
  type: ClusterIP
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432