apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chloeting
  name: mongo-db
  labels:
    app: mongo-db
spec:
  selector: 
      matchLabels: 
        app: mongo-db
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: arm64v8/mongo:4.4
          imagePullPolicy: Always
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
          envFrom:
            - configMapRef:
                name: mongodb-config
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc