apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  namespace: chloeting
spec:
  selector:
    app: mongo-db
  type: LoadBalancer
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 30332